networks:
  default:
    external: true
    name: traefik

volumes:
  db:

services:
  fe:
    image: nginx:alpine
    restart: on-failure:3
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    labels:
      - traefik.enable=true
      - traefik.http.services.mapletool-fe.loadbalancer.server.port=80
      - traefik.http.routers.mapletool-fe.rule=Host(`maple.ygh.kr`)
      - traefik.http.routers.mapletool-fe.entrypoints=websecure
      - traefik.http.routers.mapletool-fe.tls=true
      - traefik.http.routers.mapletool-fe.tls.certresolver=letsencrypt
    entrypoint:
      - sh
      - -euc
      - |
        cat <<EOF > /etc/nginx/conf.d/default.conf
        server {
          listen       80;
          server_name  localhost;
          root         /usr/share/nginx/html;

          location / {
            try_files \$$uri /index.html;
            index index.html;
          }
        }
        EOF
        nginx -g 'daemon off;'

  be:
    image: openjdk:21-jdk-slim
    restart: on-failure:3
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JASYPT_PASSWORD: ${JASYPT_PASSWORD}
    links:
      - mem
      - db
    volumes:
      - ./backend/build/libs:/opt
    labels:
      - traefik.enable=true
      - traefik.http.services.mapletool-be.loadbalancer.server.port=8080
      - traefik.http.routers.mapletool-be.rule=Host(`maple.ygh.kr`) && PathPrefix(`/api`)
      - traefik.http.routers.mapletool-be.entrypoints=websecure
      - traefik.http.routers.mapletool-be.tls=true
      - traefik.http.routers.mapletool-be.tls.certresolver=letsencrypt
    working_dir: /opt
    entrypoint: ["java", "-jar", "mapletool.jar"]

  mem:
    image: redis:alpine
    restart: on-failure:3
    tmpfs:
      - /data

  db:
    image: mysql:8.0
    restart: on-failure:3
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: maple
      LANG: C.UTF-8
    volumes:
      - db:/var/lib/mysql
      - ./db:/var/run/mysqld
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
