volumes:
  redis:
  db:

services:
  fe:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./frontend/dist:/usr/share/nginx/html

  be:
    image: openjdk:21-jdk-slim
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JASYPT_PASSWORD: ${JASYPT_PASSWORD}
    links:
      - redis
      - db
    volumes:
      - ./backend/build/libs:/opt
    working_dir: /opt
    entrypoint: ["java", "-jar", "mapletool.jar"]

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis:/data

  db:
    image: mysql:8.4.2
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: maple
      LANG: C.UTF-8
    volumes:
      - db:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
