networks:
  default:
    external: true
    name: npm

volumes:
  redis:
  db:

services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis:/data

  db:
    image: mysql:8.3.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: maple
      LANG: C.UTF-8
    volumes:
      - db:/var/lib/mysql
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci

  app:
    build: .
    image: mapletool:latest
    restart: unless-stopped
    links:
      - redis
      - db
