volumes:
  redis:
  db:

services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data

  db:
    image: mysql:8.3.0
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci

  app:
    image: openjdk:17.0.2
    restart: always
    ports:
      - 4853:8080
    links:
      - redis
      - db
    volumes:
      - WORKSPACE/build/libs/:/var/www/
    command: "java -jar -Dspring.profiles.active=prod /var/www/maple.jar"
