services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

  app:
    image: openjdk:17.0.2
    restart: always
    ports:
      - 4853:8080
    links:
      - redis
    volumes:
      - WORKSPACE/build/libs/:/var/www/
    command: "java -jar -Dspring.profiles.active=prod /var/www/maple.jar"
