import { MATERIAL_TYPE } from "./material";

export const MAX_REBIRTH_LINES = 6;

export enum REBIRTH_OPTION_TYPE {
  STR = "str",
  DEX = "dex",
  INT = "int",
  LUK = "luk",
  MAX_HP = "max_hp",
  MAX_MP = "max_mp",
  EQUIPMENT_LEVEL_DECREASE = "equipment_level_decrease",
  ARMOR = "armor",
  ATTACK_POWER = "attack_power",
  MAIGC_POWER = "magic_power",
  BOSS_DAMAGE = "boss_damage",
  DAMAGE = "damage",
  SPEED = "speed",
  JUMP = "jump",
  ALL_STAT = "all_stat",
}

export const REBIRTH_TYPE_SET: Record<string, REBIRTH_OPTION_TYPE[][]> = {
  COMMON: [
    [REBIRTH_OPTION_TYPE.STR],
    [REBIRTH_OPTION_TYPE.DEX],
    [REBIRTH_OPTION_TYPE.INT],
    [REBIRTH_OPTION_TYPE.LUK],
    [REBIRTH_OPTION_TYPE.STR, REBIRTH_OPTION_TYPE.DEX],
    [REBIRTH_OPTION_TYPE.STR, REBIRTH_OPTION_TYPE.INT],
    [REBIRTH_OPTION_TYPE.STR, REBIRTH_OPTION_TYPE.LUK],
    [REBIRTH_OPTION_TYPE.DEX, REBIRTH_OPTION_TYPE.INT],
    [REBIRTH_OPTION_TYPE.DEX, REBIRTH_OPTION_TYPE.LUK],
    [REBIRTH_OPTION_TYPE.INT, REBIRTH_OPTION_TYPE.LUK],
    [REBIRTH_OPTION_TYPE.MAX_HP],
    [REBIRTH_OPTION_TYPE.MAX_MP],
    [REBIRTH_OPTION_TYPE.EQUIPMENT_LEVEL_DECREASE],
    [REBIRTH_OPTION_TYPE.ARMOR],
    [REBIRTH_OPTION_TYPE.ATTACK_POWER],
    [REBIRTH_OPTION_TYPE.MAIGC_POWER],
    [REBIRTH_OPTION_TYPE.ALL_STAT],
  ],
  WEAPON: [[REBIRTH_OPTION_TYPE.BOSS_DAMAGE, REBIRTH_OPTION_TYPE.DAMAGE]],
  ARMOR: [[REBIRTH_OPTION_TYPE.SPEED], [REBIRTH_OPTION_TYPE.JUMP]],
};

export const REBIRTH_PROBABILITIES: Partial<Record<MATERIAL_TYPE, number[]>> = {
  POWERFUL: [0.2, 0.3, 0.36, 0.14, 0],
  ETERNAL: [0, 0.29, 0.45, 0.25, 0.01],
  BLACK: [0, 0.29, 0.45, 0.25, 0.01],
  ABYSS: [0, 0, 0.63, 0.34, 0.03],
};
