import { ItemEquipmentDetail } from "../../../types/character/itemEquipment/itemEquipment";
import CONDENSED_POWER_CRYSTAL from "../../../assets/equipment/boss/condensed-power-crystal.webp";
import AQUATIC_LETTER_EYE_ACCESSORY from "../../../assets/equipment/boss/aquatic-letter-eye-accessory.webp";
import BLACK_BEAN_MARK from "../../../assets/equipment/boss/black-bean-mark.webp";
import PAPULATUS_MARK from "../../../assets/equipment/boss/papulatus-mark.webp";
import WILL_O_THE_WISPS from "../../../assets/equipment/boss/will-o-the-wisps.webp";
import DEA_SIDUS_EARRING from "../../../assets/equipment/boss/dea-sidus-earring.webp";
import SILVER_BLOSSOM_RING from "../../../assets/equipment/boss/silver-blossom-ring.webp";
import NOBLE_IFIAS_RING from "../../../assets/equipment/boss/noble-ifias-ring.webp";
import GUARDIAN_ANGLE_RING from "../../../assets/equipment/boss/guardian-angle-ring.webp";
import HORNTAIL_NECKLACE from "../../../assets/equipment/boss/horntail-necklace.webp";
import CHAOS_HORNTAIL_NECKLACE from "../../../assets/equipment/boss/chaos-horntail-necklace.webp";
import MECHANATOR_PENDANT from "../../../assets/equipment/boss/mechanator-pendant.webp";
import DOMINATOR_PENDANT from "../../../assets/equipment/boss/dominator-pendant.webp";
import GOLDEN_COLVER_BELT from "../../../assets/equipment/boss/golden-colver-belt.webp";
import ENRAGED_ZAKUM_BELT from "../../../assets/equipment/boss/enraged-zakum-belt.webp";
import ROYAL_BLACK_METAL_SHOULDER from "../../../assets/equipment/boss/royal-black-metal-shoulder.webp";
import PINK_HOLY_CUP from "../../../assets/equipment/boss/pink-holy-cup.webp";
import STONE_OF_TERNAL_LIFE from "../../../assets/equipment/boss/stone-of-ternal-life.webp";
import CRYSTAL_VENTUS_BADGE from "../../../assets/equipment/boss/crystal-ventus-badge.webp";
import { EMPTY_OPTION } from "../equipment";

export const BOSS_ACCESSORY: Partial<ItemEquipmentDetail>[] = [
  {
    item_equipment_part: "얼굴장식",
    item_equipment_slot: "얼굴장식",
    item_name: "응축된 힘의 결정석",
    item_icon: CONDENSED_POWER_CRYSTAL,
    scroll_upgradeable_count: "5",
    cuttable_count: "10",
    item_base_option: {
      ...EMPTY_OPTION,
      base_equipment_level: 110,
      str: "5",
      dex: "5",
      int: "5",
      luk: "5",
      attack_power: "5",
      magic_power: "5",
      armor: "100",
    },
  },
  {
    item_equipment_part: "눈장식",
    item_equipment_slot: "눈장식",
    item_name: "아쿠아틱 레터 눈장식",
    item_icon: AQUATIC_LETTER_EYE_ACCESSORY,
    scroll_upgradeable_count: "3",
    cuttable_count: "10",
    item_base_option: {
      ...EMPTY_OPTION,
      base_equipment_level: 100,
      str: "6",
      dex: "6",
      int: "6",
      luk: "6",
      attack_power: "1",
      magic_power: "1",
      armor: "100",
    },
  },
  {
    item_equipment_part: "눈장식",
    item_equipment_slot: "눈장식",
    item_name: "블랙빈 마크",
    item_icon: BLACK_BEAN_MARK,
    scroll_upgradeable_count: "5",
    cuttable_count: "10",
    item_base_option: {
      ...EMPTY_OPTION,
      base_equipment_level: 135,
      str: "7",
      dex: "7",
      int: "7",
      luk: "7",
      attack_power: "1",
      magic_power: "1",
      armor: "120",
    },
  },
  {
    item_equipment_part: "눈장식",
    item_equipment_slot: "눈장식",
    item_name: "파풀라투스 마크",
    item_icon: PAPULATUS_MARK,
    scroll_upgradeable_count: "5",
    cuttable_count: "10",
    item_base_option: {
      ...EMPTY_OPTION,
      base_equipment_level: 145,
      str: "8",
      dex: "8",
      int: "8",
      luk: "8",
      attack_power: "1",
      magic_power: "1",
      armor: "150",
    },
  },
  {
    item_equipment_part: "귀고리",
    item_equipment_slot: "귀고리",
    item_name: "데아 시두스 이어링",
    item_icon: DEA_SIDUS_EARRING,
    scroll_upgradeable_count: "6",
    cuttable_count: "10",
    item_base_option: {
      ...EMPTY_OPTION,
      base_equipment_level: 130,
      str: "5",
      dex: "5",
      int: "5",
      luk: "5",
      attack_power: "2",
      magic_power: "2",
      armor: "50",
    },
  },
  {
    item_equipment_part: "귀고리",
    item_equipment_slot: "귀고리",
    item_name: "지옥의 불꽃 ",
    item_icon: WILL_O_THE_WISPS,
    scroll_upgradeable_count: "5",
    cuttable_count: "10",
    item_base_option: {
      ...EMPTY_OPTION,
      base_equipment_level: 130,
      str: "7",
      dex: "7",
      int: "7",
      luk: "7",
      max_hp: "100",
      max_mp: "100",
      attack_power: "2",
      magic_power: "2",
      armor: "100",
    },
  },
  {
    item_equipment_part: "반지",
    item_equipment_slot: "반지",
    item_name: "실버블라썸 링",
    item_icon: SILVER_BLOSSOM_RING,
    scroll_upgradeable_count: "2",
    cuttable_count: "10",
    item_base_option: {
      ...EMPTY_OPTION,
      base_equipment_level: 110,
      str: "5",
      dex: "5",
      int: "5",
      luk: "5",
      attack_power: "2",
      magic_power: "2",
    },
  },
  {
    item_equipment_part: "반지",
    item_equipment_slot: "반지",
    item_name: "고귀한 이피아의 반지",
    item_icon: NOBLE_IFIAS_RING,
    scroll_upgradeable_count: "2",
    cuttable_count: "10",
    item_base_option: {
      ...EMPTY_OPTION,
      base_equipment_level: 120,
      str: "5",
      dex: "5",
      int: "5",
      luk: "5",
      max_hp: "200",
      max_mp: "200",
      attack_power: "2",
      magic_power: "2",
    },
  },
  {
    item_equipment_part: "반지",
    item_equipment_slot: "반지",
    item_name: "가디언 엔젤 링",
    item_icon: GUARDIAN_ANGLE_RING,
    scroll_upgradeable_count: "2",
    cuttable_count: "10",
    item_base_option: {
      ...EMPTY_OPTION,
      base_equipment_level: 160,
      str: "5",
      dex: "5",
      int: "5",
      luk: "5",
      max_hp: "200",
      max_mp: "200",
      attack_power: "2",
      magic_power: "2",
    },
  },
  {
    item_equipment_part: "펜던트",
    item_equipment_slot: "펜던트",
    item_name: "혼테일의 목걸이",
    item_icon: HORNTAIL_NECKLACE,
    scroll_upgradeable_count: "2",
    cuttable_count: "10",
    item_base_option: {
      ...EMPTY_OPTION,
      base_equipment_level: 120,
      str: "7",
      dex: "7",
      int: "7",
      luk: "7",
      armor: "108",
    },
  },
  {
    item_equipment_part: "펜던트",
    item_equipment_slot: "펜던트",
    item_name: "카오스 혼테일 목걸이",
    item_icon: CHAOS_HORNTAIL_NECKLACE,
    scroll_upgradeable_count: "3",
    cuttable_count: "10",
    item_base_option: {
      ...EMPTY_OPTION,
      base_equipment_level: 120,
      str: "10",
      dex: "10",
      int: "10",
      luk: "10",
      max_hp_rate: "10%",
      max_mp_rate: "10%",
      attack_power: "2",
      magic_power: "2",
      armor: "140",
    },
  },
  {
    item_equipment_part: "펜던트",
    item_equipment_slot: "펜던트",
    item_name: "메커네이터 펜던트",
    item_icon: MECHANATOR_PENDANT,
    scroll_upgradeable_count: "2",
    cuttable_count: "10",
    item_base_option: {
      ...EMPTY_OPTION,
      base_equipment_level: 120,
      str: "10",
      dex: "10",
      int: "10",
      luk: "10",
      max_hp: "250",
      max_mp: "250",
      attack_power: "1",
      magic_power: "1",
      armor: "100",
    },
  },
  {
    item_equipment_part: "펜던트",
    item_equipment_slot: "펜던트",
    item_name: "도미네이터 펜던트",
    item_icon: DOMINATOR_PENDANT,
    scroll_upgradeable_count: "5",
    cuttable_count: "10",
    item_base_option: {
      ...EMPTY_OPTION,
      base_equipment_level: 140,
      str: "20",
      dex: "20",
      int: "20",
      luk: "20",
      max_hp_rate: "10%",
      max_mp_rate: "10%",
      attack_power: "3",
      magic_power: "3",
      armor: "100",
    },
  },
  {
    item_equipment_part: "벨트",
    item_equipment_slot: "벨트",
    item_name: "골든 클로버 벨트",
    item_icon: GOLDEN_COLVER_BELT,
    scroll_upgradeable_count: "3",
    cuttable_count: "10",
    item_base_option: {
      ...EMPTY_OPTION,
      base_equipment_level: 140,
      str: "15",
      dex: "15",
      int: "15",
      luk: "15",
      max_hp: "150",
      max_mp: "150",
      attack_power: "1",
      magic_power: "1",
      armor: "150",
    },
  },
  {
    item_equipment_part: "벨트",
    item_equipment_slot: "벨트",
    item_name: "분노한 자쿰의 벨트",
    item_icon: ENRAGED_ZAKUM_BELT,
    scroll_upgradeable_count: "3",
    cuttable_count: "10",
    item_base_option: {
      ...EMPTY_OPTION,
      base_equipment_level: 150,
      str: "18",
      dex: "18",
      int: "18",
      luk: "18",
      max_hp: "150",
      max_mp: "150",
      attack_power: "1",
      magic_power: "1",
      armor: "150",
    },
  },
  {
    item_equipment_part: "어깨장식",
    item_equipment_slot: "어깨장식",
    item_name: "로얄 블랙메탈 숄더",
    item_icon: ROYAL_BLACK_METAL_SHOULDER,
    scroll_upgradeable_count: "1",
    cuttable_count: "10",
    item_base_option: {
      ...EMPTY_OPTION,
      base_equipment_level: 120,
      str: "10",
      dex: "10",
      int: "10",
      luk: "10",
      attack_power: "6",
      magic_power: "6",
      armor: "100",
    },
  },
  {
    item_equipment_part: "포켓 아이템",
    item_equipment_slot: "포켓 아이템",
    item_name: "핑크빛 성배",
    item_icon: PINK_HOLY_CUP,
    item_base_option: {
      ...EMPTY_OPTION,
      base_equipment_level: 140,
      str: "5",
      dex: "5",
      int: "5",
      luk: "5",
      max_hp: "50",
      max_mp: "50",
      attack_power: "5",
      magic_power: "5",
    },
  },
  {
    item_equipment_part: "포켓 아이템",
    item_equipment_slot: "포켓 아이템",
    item_name: "영생의 돌",
    item_icon: STONE_OF_TERNAL_LIFE,
    item_base_option: {
      ...EMPTY_OPTION,
      base_equipment_level: 0,
      str: "3",
      dex: "3",
      int: "3",
      luk: "3",
      attack_power: "3",
      magic_power: "3",
    },
  },
  {
    item_equipment_part: "뱃지",
    item_equipment_slot: "뱃지",
    item_name: "크리스탈 웬투스 뱃지",
    item_icon: CRYSTAL_VENTUS_BADGE,
    item_base_option: {
      ...EMPTY_OPTION,
      base_equipment_level: 130,
      str: "10",
      dex: "10",
      int: "10",
      luk: "10",
      attack_power: "5",
      magic_power: "5",
      speed: "10",
      jump: "10",
    },
  },
];
