name: mapletool

volumes:
  db:

services:
  mem:
    image: redis:8.2.1-alpine
    restart: unless-stopped
    ports: ["6380:6379"]
    tmpfs:
      - /data

  db:
    image: mysql:8.0.43
    restart: unless-stopped
    ports: [ "3307:3306" ]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: maple
      LANG: C.UTF-8
    volumes:
      - db:/var/lib/mysql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
