name: mapletool

volumes:
  db:

services:
  mem:
    image: redis:alpine
    restart: unless-stopped
    tmpfs:
      - /data

  db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_EXPIRE_LOGS_DAYS: 7
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: maple
      LANG: C.UTF-8
      TZ: Asia/Seoul
    volumes:
      - db:/var/lib/mysql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
