import { ItemEquipmentDetail } from "../../../types/character/itemEquipment";
import { EMPTY_OPTION } from "../equipment";

import WARRIOR_HAT from "../../../assets/equipment/arcaneumbra/warrior/armor/hat.webp";
import WARRIOR_OVERALL from "../../../assets/equipment/arcaneumbra/warrior/armor/overall.webp";
import WARRIOR_SHOES from "../../../assets/equipment/arcaneumbra/warrior/armor/shoes.webp";
import WARRIOR_GLOVES from "../../../assets/equipment/arcaneumbra/warrior/armor/gloves.webp";
import WARRIOR_CAPE from "../../../assets/equipment/arcaneumbra/warrior/armor/cape.webp";
import WARRIOR_SHOULDER from "../../../assets/equipment/arcaneumbra/warrior/armor/shoulder.webp";

import MAGICIAN_HAT from "../../../assets/equipment/arcaneumbra/magician/armor/hat.webp";
import MAGICIAN_OVERALL from "../../../assets/equipment/arcaneumbra/magician/armor/overall.webp";
import MAGICIAN_SHOES from "../../../assets/equipment/arcaneumbra/magician/armor/shoes.webp";
import MAGICIAN_GLOVES from "../../../assets/equipment/arcaneumbra/magician/armor/gloves.webp";
import MAGICIAN_CAPE from "../../../assets/equipment/arcaneumbra/magician/armor/cape.webp";
import MAGICIAN_SHOULDER from "../../../assets/equipment/arcaneumbra/magician/armor/shoulder.webp";

import BOWMAN_HAT from "../../../assets/equipment/arcaneumbra/bowman/armor/hat.webp";
import BOWMAN_OVERALL from "../../../assets/equipment/arcaneumbra/bowman/armor/overall.webp";
import BOWMAN_SHOES from "../../../assets/equipment/arcaneumbra/bowman/armor/shoes.webp";
import BOWMAN_GLOVES from "../../../assets/equipment/arcaneumbra/bowman/armor/gloves.webp";
import BOWMAN_CAPE from "../../../assets/equipment/arcaneumbra/bowman/armor/cape.webp";
import BOWMAN_SHOULDER from "../../../assets/equipment/arcaneumbra/bowman/armor/shoulder.webp";

import THIEF_HAT from "../../../assets/equipment/arcaneumbra/thief/armor/hat.webp";
import THIEF_OVERALL from "../../../assets/equipment/arcaneumbra/thief/armor/overall.webp";
import THIEF_SHOES from "../../../assets/equipment/arcaneumbra/thief/armor/shoes.webp";
import THIEF_GLOVES from "../../../assets/equipment/arcaneumbra/thief/armor/gloves.webp";
import THIEF_CAPE from "../../../assets/equipment/arcaneumbra/thief/armor/cape.webp";
import THIEF_SHOULDER from "../../../assets/equipment/arcaneumbra/thief/armor/shoulder.webp";

import PIRATE_HAT from "../../../assets/equipment/arcaneumbra/pirate/armor/hat.webp";
import PIRATE_OVERALL from "../../../assets/equipment/arcaneumbra/pirate/armor/overall.webp";
import PIRATE_SHOES from "../../../assets/equipment/arcaneumbra/pirate/armor/shoes.webp";
import PIRATE_GLOVES from "../../../assets/equipment/arcaneumbra/pirate/armor/gloves.webp";
import PIRATE_CAPE from "../../../assets/equipment/arcaneumbra/pirate/armor/cape.webp";
import PIRATE_SHOULDER from "../../../assets/equipment/arcaneumbra/pirate/armor/shoulder.webp";

export const ARCANEUMBRA: Record<string, Partial<ItemEquipmentDetail>[]> = {
  WARRIOR: [
    {
      item_equipment_part: "모자",
      item_equipment_slot: "모자",
      item_name: "아케인셰이드 나이트햇",
      item_icon: WARRIOR_HAT,
      scroll_upgradeable_count: "11",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 200,
        str: "65",
        dex: "65",
        attack_power: "7",
        armor: "600",
        ignore_monster_armor: "15%",
      },
    },
    {
      item_equipment_part: "한벌옷",
      item_equipment_slot: "상의",
      item_name: "아케인셰이드 나이트슈트",
      item_icon: WARRIOR_OVERALL,
      scroll_upgradeable_count: "12",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 200,
        str: "85",
        dex: "85",
        attack_power: "9",
        armor: "500",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "신발",
      item_equipment_slot: "신발",
      item_name: "아케인셰이드 나이트슈즈",
      item_icon: WARRIOR_SHOES,
      scroll_upgradeable_count: "7",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 200,
        str: "40",
        dex: "40",
        attack_power: "9",
        armor: "250",
        speed: "10",
        jump: "7",
      },
    },
    {
      item_equipment_part: "장갑",
      item_equipment_slot: "장갑",
      item_name: "아케인셰이드 나이트글러브",
      item_icon: WARRIOR_GLOVES,
      scroll_upgradeable_count: "7",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 200,
        str: "40",
        dex: "40",
        attack_power: "9",
        armor: "250",
      },
    },
    {
      item_equipment_part: "망토",
      item_equipment_slot: "망토",
      item_name: "아케인셰이드 나이트케이프",
      item_icon: WARRIOR_CAPE,
      scroll_upgradeable_count: "7",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 200,
        str: "35",
        dex: "35",
        int: "35",
        luk: "35",
        attack_power: "6",
        magic_power: "6",
        armor: "450",
      },
    },
    {
      item_equipment_part: "어깨장식",
      item_equipment_slot: "어깨장식",
      item_name: "아케인셰이드 나이트숄더",
      item_icon: WARRIOR_SHOULDER,
      scroll_upgradeable_count: "1",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 200,
        str: "35",
        dex: "35",
        int: "35",
        luk: "35",
        attack_power: "20",
        magic_power: "20",
        armor: "300",
      },
    },
  ],
  MAGICIAN: [
    {
      item_equipment_part: "모자",
      item_equipment_slot: "모자",
      item_name: "아케인셰이드 매이지햇",
      item_icon: MAGICIAN_HAT,
      scroll_upgradeable_count: "11",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 200,
        int: "65",
        luk: "65",
        magic_power: "7",
        armor: "600",
        ignore_monster_armor: "15%",
      },
    },
    {
      item_equipment_part: "한벌옷",
      item_equipment_slot: "상의",
      item_name: "아케인셰이드 메이지슈트",
      item_icon: MAGICIAN_OVERALL,
      scroll_upgradeable_count: "12",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 200,
        int: "85",
        luk: "85",
        magic_power: "9",
        armor: "500",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "신발",
      item_equipment_slot: "신발",
      item_name: "아케인셰이드 메이지슈즈",
      item_icon: MAGICIAN_SHOES,
      scroll_upgradeable_count: "7",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 200,
        int: "40",
        luk: "40",
        magic_power: "9",
        armor: "250",
        speed: "10",
        jump: "7",
      },
    },
    {
      item_equipment_part: "장갑",
      item_equipment_slot: "장갑",
      item_name: "아케인셰이드 메이지글러브",
      item_icon: MAGICIAN_GLOVES,
      scroll_upgradeable_count: "7",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 200,
        int: "40",
        luk: "40",
        magic_power: "9",
        armor: "250",
      },
    },
    {
      item_equipment_part: "망토",
      item_equipment_slot: "망토",
      item_name: "아케인셰이드 메이지케이프",
      item_icon: MAGICIAN_CAPE,
      scroll_upgradeable_count: "7",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 200,
        int: "35",
        luk: "35",
        str: "35",
        dex: "35",
        magic_power: "6",
        armor: "450",
      },
    },
    {
      item_equipment_part: "어깨장식",
      item_equipment_slot: "어깨장식",
      item_name: "아케인셰이드 메이지숄더",
      item_icon: MAGICIAN_SHOULDER,
      scroll_upgradeable_count: "1",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 200,
        int: "35",
        luk: "35",
        str: "35",
        dex: "35",
        attack_power: "20",
        magic_power: "20",
        armor: "300",
      },
    },
  ],
  BOWMAN: [
    {
      item_equipment_part: "모자",
      item_equipment_slot: "모자",
      item_name: "아케인셰이드 아처햇",
      item_icon: BOWMAN_HAT,
      scroll_upgradeable_count: "11",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 200,
        dex: "65",
        str: "65",
        attack_power: "7",
        armor: "600",
        ignore_monster_armor: "15%",
      },
    },
    {
      item_equipment_part: "한벌옷",
      item_equipment_slot: "상의",
      item_name: "아케인셰이드 아처슈트",
      item_icon: BOWMAN_OVERALL,
      scroll_upgradeable_count: "12",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 200,
        dex: "85",
        str: "85",
        attack_power: "9",
        armor: "500",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "신발",
      item_equipment_slot: "신발",
      item_name: "아케인셰이드 아처슈즈",
      item_icon: BOWMAN_SHOES,
      scroll_upgradeable_count: "7",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 200,
        dex: "40",
        str: "40",
        attack_power: "9",
        armor: "250",
        speed: "10",
        jump: "7",
      },
    },
    {
      item_equipment_part: "장갑",
      item_equipment_slot: "장갑",
      item_name: "아케인셰이드 아처글러브",
      item_icon: BOWMAN_GLOVES,
      scroll_upgradeable_count: "7",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 200,
        dex: "40",
        str: "40",
        attack_power: "9",
        armor: "250",
      },
    },
    {
      item_equipment_part: "망토",
      item_equipment_slot: "망토",
      item_name: "아케인셰이드 아처케이프",
      item_icon: BOWMAN_CAPE,
      scroll_upgradeable_count: "7",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 200,
        str: "35",
        dex: "35",
        int: "35",
        luk: "35",
        attack_power: "6",
        magic_power: "6",
        armor: "450",
      },
    },
    {
      item_equipment_part: "어깨장식",
      item_equipment_slot: "어깨장식",
      item_name: "아케인셰이드 아처숄더",
      item_icon: BOWMAN_SHOULDER,
      scroll_upgradeable_count: "1",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 200,
        str: "35",
        dex: "35",
        int: "35",
        luk: "35",
        attack_power: "20",
        magic_power: "20",
        armor: "300",
      },
    },
  ],
  THIEF: [
    {
      item_equipment_part: "모자",
      item_equipment_slot: "모자",
      item_name: "아케인셰이드 시프햇",
      item_icon: THIEF_HAT,
      scroll_upgradeable_count: "11",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 200,
        luk: "65",
        dex: "65",
        attack_power: "7",
        armor: "600",
        ignore_monster_armor: "15%",
      },
    },
    {
      item_equipment_part: "한벌옷",
      item_equipment_slot: "상의",
      item_name: "아케인셰이드 시프슈트",
      item_icon: THIEF_OVERALL,
      scroll_upgradeable_count: "12",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 200,
        luk: "85",
        dex: "85",
        attack_power: "9",
        armor: "500",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "신발",
      item_equipment_slot: "신발",
      item_name: "아케인셰이드 시프슈즈",
      item_icon: THIEF_SHOES,
      scroll_upgradeable_count: "7",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 200,
        luk: "40",
        dex: "40",
        attack_power: "9",
        armor: "250",
        speed: "10",
        jump: "7",
      },
    },
    {
      item_equipment_part: "장갑",
      item_equipment_slot: "장갑",
      item_name: "아케인셰이드 시프글러브",
      item_icon: THIEF_GLOVES,
      scroll_upgradeable_count: "7",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 200,
        luk: "40",
        dex: "40",
        attack_power: "9",
        armor: "250",
      },
    },
    {
      item_equipment_part: "망토",
      item_equipment_slot: "망토",
      item_name: "아케인셰이드 시프케이프",
      item_icon: THIEF_CAPE,
      scroll_upgradeable_count: "7",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 200,
        str: "35",
        dex: "35",
        int: "35",
        luk: "35",
        attack_power: "6",
        magic_power: "6",
        armor: "450",
      },
    },
    {
      item_equipment_part: "어깨장식",
      item_equipment_slot: "어깨장식",
      item_name: "아케인셰이드 시프숄더",
      item_icon: THIEF_SHOULDER,
      scroll_upgradeable_count: "1",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 200,
        str: "35",
        dex: "35",
        int: "35",
        luk: "35",
        attack_power: "20",
        magic_power: "20",
        armor: "300",
      },
    },
  ],
  PIRATE: [
    {
      item_equipment_part: "모자",
      item_equipment_slot: "모자",
      item_name: "아케인셰이드 파이렛햇",
      item_icon: PIRATE_HAT,
      scroll_upgradeable_count: "11",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 200,
        str: "65",
        dex: "65",
        attack_power: "7",
        armor: "600",
        ignore_monster_armor: "15%",
      },
    },
    {
      item_equipment_part: "한벌옷",
      item_equipment_slot: "상의",
      item_name: "아케인셰이드 파이렛슈트",
      item_icon: PIRATE_OVERALL,
      scroll_upgradeable_count: "12",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 200,
        str: "85",
        dex: "85",
        attack_power: "9",
        armor: "500",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "신발",
      item_equipment_slot: "신발",
      item_name: "아케인셰이드 파이렛슈즈",
      item_icon: PIRATE_SHOES,
      scroll_upgradeable_count: "7",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 200,
        str: "40",
        dex: "40",
        attack_power: "9",
        armor: "250",
        speed: "10",
        jump: "7",
      },
    },
    {
      item_equipment_part: "장갑",
      item_equipment_slot: "장갑",
      item_name: "아케인셰이드 파이렛글러브",
      item_icon: PIRATE_GLOVES,
      scroll_upgradeable_count: "7",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 200,
        str: "40",
        dex: "40",
        attack_power: "9",
        armor: "250",
      },
    },
    {
      item_equipment_part: "망토",
      item_equipment_slot: "망토",
      item_name: "아케인셰이드 파이렛케이프",
      item_icon: PIRATE_CAPE,
      scroll_upgradeable_count: "7",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 200,
        str: "35",
        dex: "35",
        int: "35",
        luk: "35",
        attack_power: "6",
        magic_power: "6",
        armor: "450",
      },
    },
    {
      item_equipment_part: "어깨장식",
      item_equipment_slot: "어깨장식",
      item_name: "아케인셰이드 파이렛숄더",
      item_icon: PIRATE_SHOULDER,
      scroll_upgradeable_count: "1",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 200,
        str: "35",
        dex: "35",
        int: "35",
        luk: "35",
        attack_power: "20",
        magic_power: "20",
        armor: "300",
      },
    },
  ],
};
