import { ItemEquipmentDetail } from "../../../types/character/itemEquipment/itemEquipment";
import { EMPTY_OPTION } from "../equipment";

import WARRIOR_HAT from "../../../assets/equipment/rootabis/warrior/armor/hat.webp";
import WARRIOR_TOP from "../../../assets/equipment/rootabis/warrior/armor/top.webp";
import WARRIOR_BOTTOM from "../../../assets/equipment/rootabis/warrior/armor/bottom.webp";
import ONE_HANDED_SWORD from "../../../assets/equipment/rootabis/warrior/weapon/one-handed-sword.webp";
import ONE_HANDED_AXE from "../../../assets/equipment/rootabis/warrior/weapon/one-handed-axe.webp";
import ONE_HANDED_BLUNT from "../../../assets/equipment/rootabis/warrior/weapon/one-handed-blunt.webp";
import TWO_HANDED_SWORD from "../../../assets/equipment/rootabis/warrior/weapon/two-handed-sword.webp";
import TWO_HANDED_AXE from "../../../assets/equipment/rootabis/warrior/weapon/two-handed-axe.webp";
import TWO_HANDED_BLUNT from "../../../assets/equipment/rootabis/warrior/weapon/two-handed-blunt.webp";
import SPEAR from "../../../assets/equipment/rootabis/warrior/weapon/spear.webp";
import POLEARM from "../../../assets/equipment/rootabis/warrior/weapon/polearm.webp";
import DESPERADO from "../../../assets/equipment/rootabis/warrior/weapon/desperado.webp";
import KATANA from "../../../assets/equipment/rootabis/warrior/weapon/katana.webp";
import ARM_CANNON from "../../../assets/equipment/rootabis/warrior/weapon/arm-cannon.webp";
import BLADECASTER from "../../../assets/equipment/rootabis/warrior/weapon/bladecaster.webp";

import MAGICIAN_HAT from "../../../assets/equipment/rootabis/magician/armor/hat.webp";
import MAGICIAN_TOP from "../../../assets/equipment/rootabis/magician/armor/top.webp";
import MAGICIAN_BOTTOM from "../../../assets/equipment/rootabis/magician/armor/bottom.webp";
import WAND from "../../../assets/equipment/rootabis/magician/weapon/wand.webp";
import STAFF from "../../../assets/equipment/rootabis/magician/weapon/staff.webp";
import SHINING_ROD from "../../../assets/equipment/rootabis/magician/weapon/shining-rod.webp";
import PSY_LIMITER from "../../../assets/equipment/rootabis/magician/weapon/psy-limiter.webp";
import LUCENT_GAUNTLET from "../../../assets/equipment/rootabis/magician/weapon/lucent-gauntlet.webp";
import SCEPTER from "../../../assets/equipment/rootabis/magician/weapon/scepter.webp";
import FAN from "../../../assets/equipment/rootabis/magician/weapon/fan.webp";

import BOWMAN_HAT from "../../../assets/equipment/rootabis/bowman/armor/hat.webp";
import BOWMAN_TOP from "../../../assets/equipment/rootabis/bowman/armor/top.webp";
import BOWMAN_BOTTOM from "../../../assets/equipment/rootabis/bowman/armor/bottom.webp";
import BOW from "../../../assets/equipment/rootabis/bowman/weapon/bow.webp";
import CROSSBOW from "../../../assets/equipment/rootabis/bowman/weapon/crossbow.webp";
import DUAL_BOWGUNS from "../../../assets/equipment/rootabis/bowman/weapon/dual-bowguns.webp";
import ANCIENT_BOW from "../../../assets/equipment/rootabis/bowman/weapon/ancient-bow.webp";
import WHISPERSHOT from "../../../assets/equipment/rootabis/bowman/weapon/whispershot.webp";

import THIEF_HAT from "../../../assets/equipment/rootabis/thief/armor/hat.webp";
import THIEF_TOP from "../../../assets/equipment/rootabis/thief/armor/top.webp";
import THIEF_BOTTOM from "../../../assets/equipment/rootabis/thief/armor/bottom.webp";
import DAGGER from "../../../assets/equipment/rootabis/thief/weapon/dagger.webp";
import CLAW from "../../../assets/equipment/rootabis/thief/weapon/claw.webp";
import CANE from "../../../assets/equipment/rootabis/thief/weapon/cane.webp";
import WHIP_BLADE from "../../../assets/equipment/rootabis/thief/weapon/whip-blade.webp";
import CHAIN from "../../../assets/equipment/rootabis/thief/weapon/chain.webp";
import RITUAL_FAN from "../../../assets/equipment/rootabis/thief/weapon/ritual-fan.webp";
import CHAKRAM from "../../../assets/equipment/rootabis/thief/weapon/chakram.webp";

import PIRATE_HAT from "../../../assets/equipment/rootabis/pirate/armor/hat.webp";
import PIRATE_TOP from "../../../assets/equipment/rootabis/pirate/armor/top.webp";
import PIRATE_BOTTOM from "../../../assets/equipment/rootabis/pirate/armor/bottom.webp";
import GUN from "../../../assets/equipment/rootabis/pirate/weapon/gun.webp";
import HAND_CANNON from "../../../assets/equipment/rootabis/pirate/weapon/hand-cannon.webp";
import KNUCKLE from "../../../assets/equipment/rootabis/pirate/weapon/knuckle.webp";
import SOUL_SHOOTER from "../../../assets/equipment/rootabis/pirate/weapon/soul-shooter.webp";
import WAR_FIST from "../../../assets/equipment/rootabis/pirate/weapon/war-fist.webp";

export const ROOTABIS: Record<string, Partial<ItemEquipmentDetail>[]> = {
  WARRIOR: [
    {
      item_equipment_part: "모자",
      item_equipment_slot: "모자",
      item_name: "하이네스 워리어헬름",
      item_icon: WARRIOR_HAT,
      scroll_upgradeable_count: "11",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        str: "40",
        dex: "40",
        max_hp: "360",
        max_mp: "360",
        attack_power: "2",
        armor: "390",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "상의",
      item_equipment_slot: "상의",
      item_name: "이글아이 워리어아머",
      item_icon: WARRIOR_TOP,
      scroll_upgradeable_count: "7",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        str: "30",
        dex: "30",
        attack_power: "2",
        armor: "210",
        ignore_monster_armor: "5%",
      },
    },
    {
      item_equipment_part: "하의",
      item_equipment_slot: "하의",
      item_name: "트릭스터 워리어팬츠",
      item_icon: WARRIOR_BOTTOM,
      scroll_upgradeable_count: "7",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        str: "30",
        dex: "30",
        attack_power: "2",
        armor: "210",
        ignore_monster_armor: "5%",
      },
    },
    {
      item_equipment_part: "한손검",
      item_equipment_slot: "무기",
      item_name: "파프니르 미스틸테인",
      item_icon: ONE_HANDED_SWORD,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        str: "40",
        dex: "40",
        attack_power: "171",
        boss_damage: "30%",
        ignore_monster_armor: "5%",
      },
    },
    {
      item_equipment_part: "한손도끼",
      item_equipment_slot: "무기",
      item_name: "파프니르 트윈클리버",
      item_icon: ONE_HANDED_AXE,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        str: "40",
        dex: "40",
        attack_power: "164",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "한손둔기",
      item_equipment_slot: "무기",
      item_name: "파프니르 골디언해머",
      item_icon: ONE_HANDED_BLUNT,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        str: "40",
        dex: "40",
        attack_power: "164",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "두손검",
      item_equipment_slot: "무기",
      item_name: "파프니르 페니텐시아",
      item_icon: TWO_HANDED_SWORD,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        str: "40",
        dex: "40",
        attack_power: "171",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "두손도끼",
      item_equipment_slot: "무기",
      item_name: "파프니르 배틀클리버",
      item_icon: TWO_HANDED_AXE,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        str: "40",
        dex: "40",
        attack_power: "171",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "두손둔기",
      item_equipment_slot: "무기",
      item_name: "파프니르 라이트닝어",
      item_icon: TWO_HANDED_BLUNT,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        str: "40",
        dex: "40",
        attack_power: "171",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "창",
      item_equipment_slot: "무기",
      item_name: "파프니르 브류나크",
      item_icon: SPEAR,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        str: "40",
        dex: "40",
        attack_power: "171",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "폴암",
      item_equipment_slot: "무기",
      item_name: "파프니르 문글레이브",
      item_icon: POLEARM,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        str: "40",
        dex: "40",
        attack_power: "153",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "데스페라도",
      item_equipment_slot: "무기",
      item_name: "파프니르 데스브링어",
      item_icon: DESPERADO,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        str: "40",
        max_hp: "2000",
        attack_power: "171",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "건틀렛 리볼버",
      item_equipment_slot: "무기",
      item_name: "파프니르 빅 마운틴",
      item_icon: ARM_CANNON,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        str: "40",
        dex: "40",
        attack_power: "128",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "튜너",
      item_equipment_slot: "무기",
      item_name: "파프니르 포기브니스",
      item_icon: BLADECASTER,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        str: "40",
        dex: "40",
        attack_power: "171",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "카타나",
      item_equipment_slot: "무기",
      item_name: "파프니르 황도 마사무네",
      item_icon: KATANA,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        str: "40",
        dex: "40",
        attack_power: "164",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
  ],
  MAGICIAN: [
    {
      item_equipment_part: "모자",
      item_equipment_slot: "모자",
      item_name: "하이네스 던위치햇",
      item_icon: MAGICIAN_HAT,
      scroll_upgradeable_count: "11",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        int: "40",
        luk: "40",
        max_hp: "360",
        max_mp: "360",
        magic_power: "2",
        armor: "180",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "상의",
      item_equipment_slot: "상의",
      item_name: "이글아이 던위치로브",
      item_icon: MAGICIAN_TOP,
      scroll_upgradeable_count: "7",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        int: "30",
        luk: "30",
        magic_power: "2",
        armor: "120",
        ignore_monster_armor: "5%",
      },
    },
    {
      item_equipment_part: "하의",
      item_equipment_slot: "하의",
      item_name: "트릭스터 던위치팬츠",
      item_icon: MAGICIAN_BOTTOM,
      scroll_upgradeable_count: "7",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        int: "30",
        luk: "30",
        magic_power: "2",
        armor: "120",
        ignore_monster_armor: "5%",
      },
    },
    {
      item_equipment_part: "완드",
      item_equipment_slot: "무기",
      item_name: "파프니르 마나테이커",
      item_icon: WAND,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        int: "40",
        luk: "40",
        attack_power: "119",
        magic_power: "201",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "스태프",
      item_equipment_slot: "무기",
      item_name: "파프니르 마나크라운",
      item_icon: STAFF,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        int: "40",
        luk: "40",
        attack_power: "126",
        magic_power: "204",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "샤이닝 로드",
      item_equipment_slot: "무기",
      item_name: "파프니르 마나크래들",
      item_icon: SHINING_ROD,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        int: "40",
        luk: "40",
        attack_power: "119",
        magic_power: "201",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "ESP 리미터",
      item_equipment_slot: "무기",
      item_name: "파프니르 ESP리미터",
      item_icon: PSY_LIMITER,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        int: "40",
        luk: "40",
        attack_power: "119",
        magic_power: "201",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "매직 건틀렛",
      item_equipment_slot: "무기",
      item_name: "파프니르 매직 건틀렛",
      item_icon: LUCENT_GAUNTLET,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        int: "40",
        luk: "40",
        attack_power: "119",
        magic_power: "201",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "기억의 지팡이",
      item_equipment_slot: "무기",
      item_name: "파프니르 폴라리스 스틱",
      item_icon: SCEPTER,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        int: "40",
        luk: "40",
        attack_power: "119",
        magic_power: "201",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "부채",
      item_equipment_slot: "무기",
      item_name: "파프니르 황선 아이히메",
      item_icon: FAN,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        int: "40",
        luk: "40",
        attack_power: "126",
        magic_power: "204",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
  ],
  BOWMAN: [
    {
      item_equipment_part: "모자",
      item_equipment_slot: "모자",
      item_name: "하이네스 레인져베레",
      item_icon: BOWMAN_HAT,
      scroll_upgradeable_count: "11",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        str: "40",
        dex: "40",
        max_hp: "360",
        max_mp: "360",
        attack_power: "2",
        armor: "300",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "상의",
      item_equipment_slot: "상의",
      item_name: "이글아이 레인져후드",
      item_icon: BOWMAN_TOP,
      scroll_upgradeable_count: "7",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        dex: "30",
        str: "30",
        attack_power: "2",
        armor: "135",
        ignore_monster_armor: "5%",
      },
    },
    {
      item_equipment_part: "하의",
      item_equipment_slot: "하의",
      item_name: "트릭스터 레인져팬츠",
      item_icon: BOWMAN_BOTTOM,
      scroll_upgradeable_count: "7",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        dex: "30",
        str: "30",
        attack_power: "2",
        armor: "135",
        ignore_monster_armor: "5%",
      },
    },
    {
      item_equipment_part: "활",
      item_equipment_slot: "무기",
      item_name: "파프니르 윈드체이서",
      item_icon: BOW,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        str: "40",
        dex: "40",
        attack_power: "160",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "석궁",
      item_equipment_slot: "무기",
      item_name: "파프니르 윈드윙슈터",
      item_icon: CROSSBOW,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        str: "40",
        dex: "40",
        attack_power: "160",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "듀얼 보우건",
      item_equipment_slot: "무기",
      item_name: "파프니르 듀얼윈드윙",
      item_icon: DUAL_BOWGUNS,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        str: "40",
        dex: "40",
        attack_power: "164",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "에인션트 보우",
      item_equipment_slot: "무기",
      item_name: "파프니르 에인션트 보우",
      item_icon: ANCIENT_BOW,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        str: "40",
        dex: "40",
        attack_power: "160",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "브레스 슈터",
      item_equipment_slot: "무기",
      item_name: "파프니르 나이트체이서",
      item_icon: WHISPERSHOT,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        str: "40",
        dex: "40",
        attack_power: "160",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
  ],
  THIEF: [
    {
      item_equipment_part: "모자",
      item_equipment_slot: "모자",
      item_name: "하이네스 어새신보닛",
      item_icon: THIEF_HAT,
      scroll_upgradeable_count: "11",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        dex: "40",
        luk: "40",
        max_hp: "360",
        max_mp: "360",
        attack_power: "2",
        armor: "300",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "상의",
      item_equipment_slot: "상의",
      item_name: "이글아이 어새신셔츠",
      item_icon: THIEF_TOP,
      scroll_upgradeable_count: "7",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        luk: "30",
        dex: "30",
        attack_power: "2",
        armor: "135",
        ignore_monster_armor: "5%",
      },
    },
    {
      item_equipment_part: "하의",
      item_equipment_slot: "하의",
      item_name: "트릭스터 어새신팬츠",
      item_icon: THIEF_BOTTOM,
      scroll_upgradeable_count: "7",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        luk: "30",
        dex: "30",
        attack_power: "2",
        armor: "135",
        ignore_monster_armor: "5%",
      },
    },
    {
      item_equipment_part: "단검",
      item_equipment_slot: "무기",
      item_name: "파프니르 다마스커스",
      item_icon: DAGGER,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        dex: "40",
        luk: "40",
        attack_power: "160",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "아대",
      item_equipment_slot: "무기",
      item_name: "파프니르 리스크홀더",
      item_icon: CLAW,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        dex: "40",
        luk: "40",
        attack_power: "86",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "케인",
      item_equipment_slot: "무기",
      item_name: "파프니르 클레르시엘",
      item_icon: CANE,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        dex: "40",
        luk: "40",
        attack_power: "164",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "에너지소드",
      item_equipment_slot: "무기",
      item_name: "파프니르 스플릿엣지",
      item_icon: WHIP_BLADE,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        dex: "40",
        luk: "40",
        attack_power: "128",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "체인",
      item_equipment_slot: "무기",
      item_name: "파프니르 체인",
      item_icon: CHAIN,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        dex: "40",
        luk: "40",
        attack_power: "160",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "부채",
      item_equipment_slot: "무기",
      item_name: "파프니르 용선",
      item_icon: RITUAL_FAN,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        dex: "40",
        luk: "40",
        attack_power: "160",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "차크람",
      item_equipment_slot: "무기",
      item_name: "파프니르 차크람",
      item_icon: CHAKRAM,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        dex: "40",
        luk: "40",
        attack_power: "160",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
  ],
  PIRATE: [
    {
      item_equipment_part: "모자",
      item_equipment_slot: "모자",
      item_name: "하이네스 원더러햇",
      item_icon: PIRATE_HAT,
      scroll_upgradeable_count: "11",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        str: "40",
        dex: "40",
        max_hp: "360",
        max_mp: "360",
        attack_power: "2",
        armor: "300",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "상의",
      item_equipment_slot: "상의",
      item_name: "이글아이 원더러코트",
      item_icon: PIRATE_TOP,
      scroll_upgradeable_count: "7",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        dex: "30",
        str: "30",
        attack_power: "2",
        armor: "135",
        ignore_monster_armor: "5%",
      },
    },
    {
      item_equipment_part: "하의",
      item_equipment_slot: "하의",
      item_name: "트릭스터 원더러팬츠",
      item_icon: PIRATE_BOTTOM,
      scroll_upgradeable_count: "7",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        dex: "30",
        str: "30",
        attack_power: "2",
        armor: "135",
        ignore_monster_armor: "5%",
      },
    },
    {
      item_equipment_part: "건",
      item_equipment_slot: "무기",
      item_name: "파프니르 첼리스카",
      item_icon: GUN,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        str: "40",
        dex: "40",
        attack_power: "125",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "너클",
      item_equipment_slot: "무기",
      item_name: "파프니르 펜리르탈론",
      item_icon: KNUCKLE,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        str: "40",
        dex: "40",
        attack_power: "128",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "핸드캐논",
      item_equipment_slot: "무기",
      item_name: "파프니르 러스터캐논",
      item_icon: HAND_CANNON,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        str: "40",
        dex: "40",
        attack_power: "175",
        armor: "121",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "소울슈터",
      item_equipment_slot: "무기",
      item_name: "파프니르 엔젤릭슈터",
      item_icon: SOUL_SHOOTER,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        str: "40",
        dex: "40",
        attack_power: "128",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "에너지소드",
      item_equipment_slot: "무기",
      item_name: "파프니르 스플릿엣지",
      item_icon: WHIP_BLADE,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        str: "40",
        dex: "40",
        attack_power: "128",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
    {
      item_equipment_part: "무권",
      item_equipment_slot: "무기",
      item_name: "파프니르 무권",
      item_icon: WAR_FIST,
      scroll_upgradeable_count: "8",
      cuttable_count: "10",
      item_base_option: {
        ...EMPTY_OPTION,
        base_equipment_level: 150,
        str: "40",
        dex: "40",
        attack_power: "128",
        boss_damage: "30%",
        ignore_monster_armor: "10%",
      },
    },
  ],
};
