networks:
  default:
    external: true
    name: traefik

services:
  be:
    image: openjdk:21-jdk
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JASYPT_PASSWORD: ${JASYPT_PASSWORD:?error}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 1s
      timeout: 1s
      retries: 60
    labels:
      traefik.enable: 1
      traefik.http.services.mapletool-be.loadbalancer.server.port: 8080
      traefik.http.routers.mapletool-be.rule: Host(`maple.ygh.kr`) && PathPrefix(`/api`)
      traefik.http.routers.mapletool-be.entrypoints: websecure
      traefik.http.routers.mapletool-be.tls: 1
      traefik.http.routers.mapletool-be.tls.certresolver: letsencrypt
    volumes:
      - ../backend/build/libs:/opt:ro
    working_dir: /opt
    entrypoint: [java, -jar, mapletool.jar]
