# docker compose -f docker-compose-bu.yaml run --rm (backup|restore)

networks:
  default:
    external: true
    name: traefik

volumes:
  mapletool_db:
    external: true

services:
  backup:
    image: perconalab/percona-xtrabackup:8.0
    user: 999:999
    environment:
      TZ: Asia/Seoul
    volumes:
      - mapletool_db:/var/lib/mysql
      - ./backup:/backup
    entrypoint:
      - /bin/bash
      - -c
      - |
        set -e
        NEW_DIR=/backup/`date "+%Y%m%d-%H%M%S-%Z"`
        LASTEST_DIR=`ls -d /backup/*/ 2>/dev/null | tail -n 1`

        if [[ `date "+%d"` -eq 01 || -z $${LASTEST_DIR} ]]; then
          xtrabackup --backup --compress --host=db --user=root \
            --password=${MYSQL_ROOT_PASSWORD} \
            --target-dir=$${NEW_DIR} \
            && ls -d /backup/*/ 2>/dev/null \
              | grep -v $${NEW_DIR} | xargs rm -rf
        else
          xtrabackup --backup --compress --host=db --user=root \
            --password=${MYSQL_ROOT_PASSWORD} \
            --target-dir=$${NEW_DIR} \
            --incremental-basedir=$${LASTEST_DIR}
        fi

  restore:
    image: perconalab/percona-xtrabackup:8.0
    user: 999:999
    volumes:
      - mapletool_db:/var/lib/mysql
      - ./backup:/backup
    entrypoint:
      - bash
      - -c
      - |
        set -e
        FULL_DIR=`ls -d /backup/*/ 2>/dev/null | head -n 1`
        LAST_DIR=`ls -d /backup/*/ 2>/dev/null | tail -n 1`
        if [ -z "$${FULL_DIR}" ]; then
          exit 1
        fi

        xtrabackup --decompress --target-dir=$${FULL_DIR}
        if [ $${FULL_DIR} = $${LAST_DIR} ]; then
          xtrabackup --prepare --target-dir=$${FULL_DIR}
        else
          xtrabackup --prepare --target-dir=$${FULL_DIR} --apply-log-only

          for DIR in `ls -d /backup/*/ | tail -n +2 | head -n -1`; do
            xtrabackup --decompress --target-dir=$${DIR}
            xtrabackup --prepare --target-dir=$${FULL_DIR} \
              --incremental-dir=$${DIR} --apply-log-only
          done

          xtrabackup --decompress --target-dir=$${LAST_DIR}
          xtrabackup --prepare --target-dir=$${FULL_DIR} \
            --incremental-dir=$${LAST_DIR}
        fi

        rm -rf /var/lib/mysql/*
        xtrabackup --copy-back --target-dir=$${FULL_DIR}
        rm -rf /backup/*
