name: mapletool

networks:
  default:
    external: true
    name: traefik

volumes:
  db:

services:
  mem:
    image: redis:alpine
    restart: unless-stopped
    tmpfs:
      - /data

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_EXPIRE_LOGS_DAYS: 7
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: maple
      LANG: C.UTF-8
      TZ: Asia/Seoul
    volumes:
      - db:/var/lib/mysql
      - ./db:/var/run/mysqld
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
