import {
  ItemEquipmentDetail,
  ItemEquipmentOption,
} from "../../types/character/itemEquipment/itemEquipment";

export const SLOT_GRID = [
  ["반지4", "", "모자", "", "엠블렘"],
  ["반지3", "펜던트2", "얼굴장식", "", "뱃지"],
  ["반지2", "펜던트", "눈장식", "귀고리", "훈장"],
  ["반지1", "무기", "상의", "어깨장식", "보조무기"],
  ["포켓 아이템", "벨트", "하의", "장갑", "망토"],
  ["", "", "신발", "", "기계 심장"],
];
export const TOOLTIP_COLORS = {
  TOTAL: "#66ffff",
  ADD: "#d4ff00",
  ETC_POSITIVE: "#aaaaff",
  ETC_NEAGTIVE: "#fe0066",
  STAR: "#ffcc00",
  SOUL: "#fefe44",
};

export const EMPTY_OPTION: ItemEquipmentOption = {
  str: "0",
  dex: "0",
  intellect: "0",
  int: "0",
  luk: "0",
  max_hp: "0",
  max_mp: "0",
  attack_power: "0",
  magic_power: "0",
  armor: "0",
  speed: "0",
  jump: "0",
  boss_damage: "0",
  ignore_monster_armor: "0",
  all_stat: "0",
  damage: "0",
  equipment_level_decrease: 0,
  max_hp_rate: "0",
  max_mp_rate: "0",
  base_equipment_level: 0,
};

export const EMPTY_DETAIL: ItemEquipmentDetail = {
  item_equipment_part: "",
  item_equipment_slot: "",
  item_name: "",
  item_icon: "",
  item_description: "",
  item_shape_name: "",
  item_shape_icon: "",
  item_gender: "",
  item_total_option: EMPTY_OPTION,
  item_base_option: EMPTY_OPTION,
  potential_option_grade: "",
  additional_potential_option_grade: "",
  potential_option_1: "",
  potential_option_2: "",
  potential_option_3: "",
  additional_potential_option_1: "",
  additional_potential_option_2: "",
  additional_potential_option_3: "",
  equipment_level_increase: 0,
  item_exceptional_option: EMPTY_OPTION,
  item_add_option: EMPTY_OPTION,
  growth_exp: 0,
  growth_level: 0,
  scroll_upgrade: "0",
  cuttable_count: "255",
  golden_hammer_flag: "미적용",
  scroll_resilience_count: "0",
  scroll_upgradeable_count: "0",
  soul_name: "",
  soul_option: "",
  item_etc_option: EMPTY_OPTION,
  starforce: "0",
  starforce_scroll_flag: "미사용",
  item_starforce_option: EMPTY_OPTION,
  special_ring_level: 0,
  date_expire: "",
};
