networks:
  default:
    external: true
    name: traefik

services:
  fe:
    image: nginx:alpine
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
    labels:
      traefik.enable: 1
      traefik.http.services.mapletool-fe.loadbalancer.server.port: 80
      traefik.http.routers.mapletool-fe.rule: Host(`maple.ygh.kr`)
      traefik.http.routers.mapletool-fe.entrypoints: websecure
      traefik.http.routers.mapletool-fe.tls: 1
      traefik.http.routers.mapletool-fe.tls.certresolver: letsencrypt
    volumes:
      - ../../frontend/dist:/usr/share/nginx/html:ro
    entrypoint:
      - sh
      - -euc
      - |
        cat <<EOF > /etc/nginx/conf.d/default.conf
        server {
          listen       80;
          server_name  localhost;
          root         /usr/share/nginx/html;

          location / {
            try_files /\$$uri /index.html;
            index index.html;
          }
        }
        EOF
        nginx -g 'daemon off;'
