networks:
  default:
    external: true
    name: traefik

services:
  fe:
    image: mapletool-fe
    build:
      context: ../../frontend
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
    labels:
      traefik.enable: "true"
      traefik.http.services.mapletool-fe.loadbalancer.server.port: 80
      traefik.http.routers.mapletool-fe.rule: Host(`maple.ygh.kr`)
      traefik.http.routers.mapletool-fe.entrypoints: websecure
      traefik.http.routers.mapletool-fe.tls: "true"
      traefik.http.routers.mapletool-fe.tls.certresolver: letsencrypt
