volumes:
  redis:
  db:

services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  db:
    image: mysql:8.4.2
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: maple
      LANG: C.UTF-8
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
