name: mapletool

volumes:
  db:

services:
  mem:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    tmpfs:
      - /data

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: maple
      LANG: C.UTF-8
      TZ: Asia/Seoul
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
