spring:
  jpa.open-in-view: false
  data.redis.repositories.enabled: false
  web.resources.add-mappings: false

  cloud.openfeign.client.config:
    open-api:
      url: https://open.api.nexon.com/maplestory/v1
    maple:
      url: https://maplestory.nexon.com

resilience4j.ratelimiter.instances:
  maple:
    limitForPeriod: 1
    limitRefreshPeriod: 10s
    timeoutDuration: 10m

jasypt.encryptor.password: ${JASYPT_PASSWORD}
