nexon:
  api:
    url: https://open.api.nexon.com
    key: ''

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mapletool

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
