jasypt.encryptor.password: ${JASYPT_PASSWORD}

spring:
  application.name: mapletool
  jpa.open-in-view: false
  web.resources.add-mappings: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/maple
    username: root
    password: root

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update

  cloud.openfeign:
    okhttp.enabled: true
    client.config:
      open-api:
        url: https://open.api.nexon.com/maplestory/v1
        logger-level: basic
        default-request-headers:
          x-nxopen-api-key: ENC(GKf854Z4Hg+gfvkGA4PuoAzMLGliGyDw5hRNItAIH1YWBv8umSbEO+noyoURAcg8lGhPkAN44tZWxKV7ishLMASRHVC8zeShcG254k2qgBs6P5wL75AnGD2YPX38R2UY3HGZk/W1Rn4c6jLw98CDdAhSq17YWK34qPoxvASnGjXmDqxqWZ6DIB9kFyj8B872)
      maple:
        url: https://maplestory.nexon.com/N23Ranking/World/Total
        logger-level: basic
      proxy-scrape:
        url: https://api.proxyscrape.com/v4/free-proxy-list/get
        default-query-parameters:
          request: display_proxies
          protocol: http
          proxy_format: protocolipport
          format: text
          timeout: 2000

logbook.strategy: without-body
logging.level:
  org.zalando.logbook: TRACE
  org.springframework.cache: TRACE

management:
  metrics.tags:
    application: ${spring.application.name}
    instance: dev
  otlp.metrics.export:
    base-time-unit: seconds
    url: https://otlp-gateway-prod-ap-northeast-0.grafana.net/otlp/v1/metrics
    headers:
      Authorization: ENC(9pQPTJR+Wnh8dSDKuCst02vDvpukqwxirfrBNrLgVzJ3xeb8l8XFzpDctGJFI+3yVg/dV+Ve0fcEa688KWACunUD1C2U+e0yNChkmasWhA+XCOvw82fwiaWEcqUUWCpRvSTOmqokjW8/ZVb9pseq+X8urKzPIz+dDpnVdTmkUZSZHf4kGv4/dSKs4T1XN7o3nVF2NLmjz5RrkQ0LbBX55toW7PPTKdRxawIoJcTzBERgABH/AQR3ziSARG0pBSHVhuhiqK0CzTKFtvCL4IdzLZSA8SBcCPs0KTMWz/2hOdn9N8x9LMXsA/KFNBdyuARuiIYNunj3Bu0KlFMwrNZwcEktrStAT9mEKNxOo7bDpQw=)