spring:
  jpa:
    open-in-view: false

  data:
    redis:
      repositories:
        enabled: false

  web:
    resources:
      add-mappings: false

  cloud:
    openfeign:
      client:
        config:
          nexon:
            url: https://open.api.nexon.com/maplestory/v1

jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}
