spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/maple
    username: root
    password: root

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  cloud:
    openfeign:
      client:
        config:
          nexon:
            logger-level: full
            default-request-headers:
              x-nxopen-api-key:
                - ENC(GKf854Z4Hg+gfvkGA4PuoAzMLGliGyDw5hRNItAIH1YWBv8umSbEO+noyoURAcg8lGhPkAN44tZWxKV7ishLMASRHVC8zeShcG254k2qgBs6P5wL75AnGD2YPX38R2UY3HGZk/W1Rn4c6jLw98CDdAhSq17YWK34qPoxvASnGjXmDqxqWZ6DIB9kFyj8B872)

logging:
  level:
    kr.ygh: DEBUG
    org.zalando.logbook: TRACE
    org.springframework.cache: TRACE
