spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:maple

  jpa:
    open-in-view: false

  data:
    redis:
      repositories:
        enabled: false

jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}
