spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:maple

  jpa:
    open-in-view: false

  data:
    redis:
      repositories:
        enabled: false

  cloud:
    openfeign:
      client:
        config:
          nexon:
            url: https://open.api.nexon.com/maplestory/v1

jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}
