nexon:
  key: ENC(ej5wNEnAUWn2hBrQwpjYqKYHZoe5betUJoXZlKbvFjsJcLZJpy5mIUACqaZhibPmcqxFT0u7L2KZXP2FRsjpD8MuWzuPa5iF8Dvw/5ubIG8L/DUaLxIUbDZv+gZRL7E0vGXOoGtRAF7PD5j3VWDNAsc4MmjyNfTR9xpZvy6elTxoE1wMHx6oj7gSRYYjo0dr)

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/maple
    username: ENC(E2nEwnsONS8RxOb2lghqn21+hRYntM9DLKfLGyGNV0vineoU7JaHHdDUKHnSltyN)
    password: ENC(C4/9FfrVecykUvOIurUuZULe+WH490Ny8hn1AQsRUFs7+LWgQ57Cid2JQZzgHbwf)

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
