name: Backend Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - backend/**
      - .github/workflows/be-cd.yaml
      - docker-compose-be.yaml
      - docker-compose-db.yaml

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Build
        working-directory: backend
        run: |
          chmod +x gradlew
          ./gradlew build -x test

      - name: Copy jar
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: backend/build/libs/, backend/Dockerfile, docker-compose-be.yaml, docker-compose-db.yaml
          target: ~/${{ github.event.repository.name }}

      - name: Setup environment variables
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd ~/${{ github.event.repository.name }}
            echo "JASYPT_PASSWORD=${{ secrets.JASYPT_PASSWORD }}" > .env
            echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env

      - name: Update db
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd ~/${{ github.event.repository.name }}
            export $(cat .env)
            docker compose -f docker-compose-db.yaml pull
            docker compose -f docker-compose-db.yaml up -d

      - name: Update be
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd ~/${{ github.event.repository.name }}
            export $(cat .env)
            docker compose -f docker-compose-be.yaml build
            STACK=$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')
            if docker service ls | grep -qw ${STACK}_be; then
              docker service update --force --detach=false ${STACK}_be
            else
              docker stack deploy -c docker-compose-be.yaml ${STACK}
            fi