name: Backend Deploy

on:
  push:
    branches:
      - main
    paths:
      - backend/**
      - server/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Build
        working-directory: backend
        run: |
          chmod +x gradlew
          ./gradlew build -x test

      - name: Setup environment variables
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd ~/${{ github.event.repository.name }}
            echo "JASYPT_PASSWORD=${{ secrets.JASYPT_PASSWORD }}" > .env
            echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env

      - name: Copy jar
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: backend/build/libs/, server/
          target: ~/${{ github.event.repository.name }}

      - name: Restart docker compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd ~/${{ github.event.repository.name }}/server
            docker compose -f docker-compose-db.yaml pull
            docker compose -f docker-compose-be.yaml pull
            docker compose -f docker-compose-be.yaml down
            docker compose -f docker-compose-be.yaml up -d
            docker compose -f docker-compose-db.yaml up -d
