name: Frontend Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - frontend/**
      - .github/workflows/fe-cd.yaml
      - server/docker/docker-compose-fe.yaml

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Nodejs 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install modules
        working-directory: frontend
        run: npm ci

      - name: Build
        working-directory: frontend
        run: npm run build

      - name: Copy dist
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: frontend/dist/, frontend/Dockerfile, frontend/nginx.conf, server/docker/
          target: ~/${{ github.event.repository.name }}

      - name: Update fe
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd ~/${{ github.event.repository.name }}/server/docker

            docker compose -f docker-compose-fe.yaml build

            STACK=$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')
            docker service ls | grep -iw ${STACK}_fe \
              && docker service update --force ${STACK}_fe \
              || docker stack deploy -c docker-compose-fe.yaml ${STACK}

            STATUS=$(docker service inspect ${STACK}_fe --format {{.UpdateStatus.State}} 2>/dev/null || echo "")
            if [[ -n "${STATUS}" && ${STATUS} != "completed" ]]; then
              echo "Service update status is '${STATUS}', not completed. Exiting."
              exit 1
            fi
